<script setup lang="ts">
import { computed,onMounted,ref,watch } from 'vue'
import { AudioLines,Download,Search,Plus,Settings2,X,Trash2,Star,Upload,ArrowRight,Headphones } from 'lucide-vue-next'
import JSZip from 'jszip'
import { initialNPCs } from './data'
import { loadProject,saveProject,takesDB,type Take } from './storage'
import { projectSchema,voices,models } from '../shared/schema'
const npcs=ref(loadProject(initialNPCs)),selected=ref(npcs.value[0]?.id??''),query=ref(''),language=ref<'ru'|'en'>('ru')
const npc=computed(()=>npcs.value.find(x=>x.id===selected.value)!),filtered=computed(()=>npcs.value.filter(x=>(x.name+' '+x.role).toLowerCase().includes(query.value.toLowerCase())))
const takes=ref<Take[]>([]),busy=ref(false),notice=ref(''),accessOpen=ref(false),token=ref(''),compare=ref<string[]>([]),edit=ref(false),tab=ref<'studio'|'casting'>('studio')
const urls=ref<Record<string,string>>({})
const currentTakes=computed(()=>takes.value.filter(t=>t.npcId===selected.value).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)))
const compared=computed(()=>takes.value.filter(t=>compare.value.includes(t.id)))
watch(npcs,()=>{try{saveProject(npcs.value)}catch{notice.value='Не удалось сохранить настройки. Экспортируйте JSON.'}},{deep:true})
onMounted(async()=>{try{takes.value=await takesDB('read');takes.value.forEach(t=>urls.value[t.id]=URL.createObjectURL(t.blob))}catch{notice.value='Хранилище аудио недоступно в этом браузере.'}})
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportProject(){download(new Blob([JSON.stringify({version:1,npcs:npcs.value},null,2)],{type:'application/json'}),'farlands-project.json')}
async function importProject(e:Event){const input=e.target as HTMLInputElement,file=input.files?.[0];if(!file)return;try{if(file.size>1000000)throw Error();const data=projectSchema.parse(JSON.parse(await file.text()));npcs.value=data.npcs;selected.value=data.npcs[0]?.id??'';notice.value='Проект импортирован'}catch{notice.value='Некорректный файл проекта'}input.value=''}
function addNPC(){const id='npc_'+crypto.randomUUID().slice(0,8);npcs.value.push({id,name:'Новый персонаж',role:'NPC',text:'',settings:{voice:'Kore',model:models[0],emotion:'Спокойная',pace:1,direction:''}});selected.value=id;edit.value=true;tab.value='studio'}
async function generate(){if(!token.value){accessOpen.value=true;return}busy.value=true;notice.value='';const snapshot={npcId:npc.value.id,text:npc.value.text,settings:structuredClone({...npc.value.settings}),language:language.value};try{const r=await fetch('/api/tts',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token.value}`},body:JSON.stringify({...snapshot.settings,text:snapshot.text,language:snapshot.language})});if(!r.ok){const data=await r.json();throw Error(data.error??'Ошибка генерации')}const take:Take={...snapshot,id:crypto.randomUUID(),createdAt:new Date().toISOString(),blob:await r.blob(),favorite:false};await takesDB('put',take);takes.value.push(take);urls.value[take.id]=URL.createObjectURL(take.blob);notice.value='Дубль создан и сохранён'}catch(e){notice.value=e instanceof Error?e.message:'Ошибка генерации'}finally{busy.value=false}}
async function removeTake(t:Take){try{await takesDB('delete',undefined,t.id);takes.value=takes.value.filter(x=>x.id!==t.id);compare.value=compare.value.filter(x=>x!==t.id);URL.revokeObjectURL(urls.value[t.id]!);delete urls.value[t.id]}catch{notice.value='Не удалось удалить дубль'}}
async function favorite(t:Take){try{await takesDB('put',{...t,favorite:!t.favorite});t.favorite=!t.favorite}catch{notice.value='Не удалось сохранить выбор'}}
function toggleCompare(id:string){if(compare.value.includes(id))compare.value=compare.value.filter(x=>x!==id);else if(compare.value.length<2)compare.value.push(id);else notice.value='Для сравнения выберите два дубля'}
async function exportGodot(){try{const zip=new JSZip();const manifest={version:1,project:'FARM & FARLANDS',audio_format:'wav',npcs:npcs.value,takes:takes.value.map(t=>({id:t.id,npc_id:t.npcId,text:t.text,settings:t.settings,language:t.language,favorite:t.favorite,created_at:t.createdAt,audio:`res://voice/audio/${t.npcId}_${t.id}.wav`}))};for(const t of takes.value)zip.file(`voice/audio/${t.npcId}_${t.id}.wav`,t.blob);zip.file('voice/manifest.json',JSON.stringify(manifest,null,2));zip.file('voice/README.txt','Copy voice/ into your Godot project. Read manifest.json with JSON.parse_string; load the audio path with load(). Audio is 24 kHz mono WAV.');download(await zip.generateAsync({type:'blob'}),'farlands-godot.zip');notice.value='Пакет Godot экспортирован'}catch{notice.value='Не удалось экспортировать пакет'}}
function pauseOthers(e:Event){document.querySelectorAll('audio').forEach(a=>{if(a!==e.target)a.pause()})}
</script>

<template>
 <div class="studio">
  <header><div><span class="eyebrow">FARM & FARLANDS / AUDIO DEPARTMENT</span><h1>Voice Studio<span class="crosshair">⌖</span></h1></div><div class="header-actions"><button @click="accessOpen=true"><Settings2 :size="15"/> Доступ к API</button><button @click="exportProject"><Download :size="15"/> JSON</button><button class="primary" @click="exportGodot"><Download :size="15"/> Экспорт в Godot</button></div></header>
  <nav><button :class="{chosen:tab==='studio'}" @click="tab='studio'"><AudioLines :size="16"/> Студия</button><button :class="{chosen:tab==='casting'}" @click="tab='casting'">Кастинг озвучки</button><span>GOOGLE · GEMINI 3.8 FLASH TTS</span><small>{{npcs.length}} ПЕРСОНАЖЕЙ · ЛОКАЛЬНЫЙ ПРОЕКТ</small></nav>
  <section v-if="tab==='casting'" class="casting"><div class="section-heading"><span class="eyebrow">КАСТИНГ ОЗВУЧКИ</span><button @click="addNPC"><Plus :size="15"/> Персонаж</button></div><p v-if="!npcs.length" class="cast-empty">Каталог пока пуст. Добавьте персонажа, чтобы начать кастинг голоса.</p><div v-else class="cast-head"><span>ПЕРСОНАЖ</span><span>ГОЛОС GOOGLE</span><span>СТИЛЬ И ИНТОНАЦИЯ</span></div><button v-for="(n,i) in npcs" :key="n.id" class="cast-row" @click="selected=n.id;tab='studio'"><span class="cast-name"><span class="portrait small-portrait" >{{String(i+1).padStart(2,'0')}}</span><span><strong>{{n.name}}</strong><small>{{n.role}}</small></span></span><span class="cast-voice"><ArrowRight :size="20"/><strong>{{n.settings.voice}}</strong></span><em>{{n.settings.direction}}</em></button></section>
  <div v-else class="layout">
   <aside class="catalog panel"><div class="panel-title"><h3>Персонажи <small>{{npcs.length}}</small></h3><button class="icon" @click="addNPC" aria-label="Добавить NPC"><Plus :size="18"/></button></div><label class="search"><Search :size="15"/><input v-model="query" placeholder="Найти персонажа" aria-label="Поиск NPC"/></label><button v-for="(n,i) in filtered" :key="n.id" class="npc-row" :class="{active:selected===n.id}" @click="selected=n.id;edit=false"><span class="portrait small-portrait" >{{String(i+1).padStart(2,'0')}}</span><span><strong>{{n.name}}</strong><small>{{n.role}}</small></span><i v-if="takes.some(t=>t.npcId===n.id)"/></button><p v-if="!filtered.length" class="hint">Никого не найдено</p><label class="import"><Upload :size="14"/> Импорт проекта<input type="file" accept="application/json,.json" @change="importProject"/></label></aside>
   <main v-if="npc" class="editor">
    <section class="character panel"><div class="character-top"><div class="portrait" >{{npc.name.slice(0,1)}}</div><div><span class="eyebrow">ПРОФИЛЬ ПЕРСОНАЖА</span><h2>{{npc.name}}</h2><p>{{npc.role}}</p></div><button class="icon ml-auto" @click="edit=!edit" aria-label="Редактировать персонажа"><Settings2 :size="17"/></button></div><div v-if="edit" class="fields"><label>Имя<input v-model="npc.name" maxlength="80"/></label><label>Роль<input v-model="npc.role" maxlength="120"/></label></div><p class="character-direction">{{npc.settings.direction}}</p></section>
    <section class="panel settings"><div class="panel-title"><h3>Кастинг голоса</h3><span class="step">01 / VOICE</span></div><div class="fields"><label>Голос Gemini<select v-model="npc.settings.voice"><option v-for="v in voices" :key="v">{{v}}</option></select></label><label>Модель<select v-model="npc.settings.model"><option v-for="m in models" :value="m" :key="m">{{m.includes('lite')?'Gemini 3.8 Flash-Lite TTS':'Gemini 3.8 Flash TTS'}}</option></select></label></div><label>Эмоция и настроение<input v-model="npc.settings.emotion" maxlength="100"/></label><label class="range-label">Темп речи <span>{{npc.settings.pace.toFixed(2)}}×</span><input v-model.number="npc.settings.pace" type="range" min="0.5" max="1.5" step="0.05"/></label><label>Режиссёрские указания<textarea v-model="npc.settings.direction" rows="2" maxlength="1000"/></label><p class="hint">Темп и стиль — указания модели, точное соблюдение не гарантируется.</p></section>
    <section class="panel script"><div class="panel-title"><h3>Тестовая реплика</h3><select v-model="language" aria-label="Язык реплики" class="language"><option value="ru">RU</option><option value="en">EN</option></select></div><textarea v-model="npc.text" maxlength="600" rows="4" aria-label="Текст реплики"/><div class="script-footer"><span>{{npc.text.length}} / 600 символов</span><button class="primary" :disabled="busy||!npc.text.trim()" @click="generate"><AudioLines :size="17"/>{{busy?'Генерация…':'Создать дубль'}}</button></div><p class="hint">API может тарифицироваться. Проверьте квоты проекта в Google AI Studio.</p></section>
   </main><main v-else class="editor panel empty-project"><AudioLines :size="40"/><span class="eyebrow">ВАША СТУДИЯ ГОЛОСОВ</span><h2>Начните с персонажа</h2><p>Добавьте NPC, выберите голос и напишите первую реплику.<br/>Здесь будут ваши персонажи, ваши настройки и ваши дубли.</p><button class="primary" @click="addNPC"><Plus :size="16"/> Добавить персонажа</button></main>
   <aside class="takes panel"><div class="panel-title"><h3><Headphones :size="17"/> Дубли <small>{{currentTakes.length}}</small></h3></div><p class="subtitle">Слушайте. Сравнивайте. Выбирайте.</p><div v-if="!currentTakes.length" class="takes-empty"><div class="wave"><span v-for="i in 21" :key="i" :style="{height:(10+Math.sin(i*1.7)**2*38)+'px'}"/></div><h4>Голос ещё не записан</h4><p>Создайте первый дубль и найдите звучание своего персонажа.</p><span class="pill">WAV · 24 kHz · MONO</span></div><article v-for="(t,i) in currentTakes" :key="t.id" class="take"><div class="take-title"><strong>Дубль {{currentTakes.length-i}}</strong><button class="icon" @click="favorite(t)" aria-label="Выбрать дубль" :class="{gold:t.favorite}"><Star :size="16" :fill="t.favorite?'currentColor':'none'"/></button></div><small>{{t.settings.voice}} · {{t.settings.pace}}× · {{new Date(t.createdAt).toLocaleTimeString('ru')}}</small><p>{{t.text}}</p><audio controls :src="urls[t.id]" @play="pauseOthers"/><div class="take-actions"><label><input type="checkbox" :checked="compare.includes(t.id)" @change="toggleCompare(t.id)"/> Сравнить</label><button class="icon" @click="download(t.blob,`${t.npcId}_${t.id}.wav`)" aria-label="Скачать WAV"><Download :size="16"/></button><button class="icon" @click="removeTake(t)" aria-label="Удалить дубль"><Trash2 :size="15"/></button></div></article><p class="takes-note">Настройки и аудио сохраняются в этом браузере. Экспортируйте пакет Godot для резервной копии.</p></aside>
  </div>
  <footer><span>FARM & FARLANDS</span><span>VOICE STUDIO</span></footer>
  <div v-if="notice" class="toast" role="status">{{notice}}<button class="icon" @click="notice=''" aria-label="Закрыть уведомление"><X :size="16"/></button></div>
  <div v-if="accessOpen" class="overlay" @click.self="accessOpen=false"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="access-title"><button class="icon close" @click="accessOpen=false" aria-label="Закрыть"><X/></button><h2 id="access-title">Доступ к студии</h2><p>Введите код доступа владельца сервера. Ключ Gemini хранится только на сервере.</p><label>Код доступа<input v-model="token" type="password" autocomplete="off" @keyup.enter="accessOpen=false"/></label><p class="hint">Код остаётся в памяти вкладки и не сохраняется в проекте.</p><button class="primary" @click="accessOpen=false">Продолжить</button></section></div>
  <div v-if="compared.length" class="compare"><div class="panel-title"><h3>Сравнение A / B</h3><button class="icon" @click="compare=[]" aria-label="Закрыть сравнение"><X/></button></div><div class="compare-grid"><div v-for="(t,i) in compared" :key="t.id"><strong>{{i?'B':'A'}} · {{t.settings.voice}} · {{t.settings.emotion}}</strong><audio controls :src="urls[t.id]" @play="pauseOthers"/></div></div></div>
 </div>
</template>


